name: action-update-version

run-name: ${{ github.actor }} is updating version.txt for latest release

on:
   # Triggers the workflow on release
  release:
    types: [released]
  workflow_dispatch: # Allow manual trigger workflows

jobs:
  check:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      # output as this job,
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs
      stable_ver: ${{ steps.check_ver.outputs.stable_ver }}
      is_update: ${{ steps.check_ver.outputs.is_update }}
      result: ${{ steps.check_ver.outputs.result }}
    steps:
      - uses: mogeko/latest-version@v1
        id: check_ver
        with:
          repo: $OWNER/$REPO
        env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              OWNER: ${{ github.repository_owner }}
              REPO: ${{ github.event.repository.name }}

  print: # Just for show the output
    name: Print the result from check
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: |
          echo '${{ needs.check.outputs.stable_ver }}'
          echo '${{ needs.check.outputs.is_update }}'
          echo '${{ needs.check.outputs.result }}' | jq '.'
